services:
  redis:
    image: redis:7-alpine
    container_name: ejercicio_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data_ej:/data
    networks:
      - cache_network_ej
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:15-alpine
    container_name: ejercicio_redis_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cachedb
    volumes:
      - pg_data_ej:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    networks:
      - cache_network_ej
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: app_fastapi
    restart: always
    ports:
      - "5001:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: cachedb
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - cache_network_ej
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data_ej:
  pg_data_ej:

networks:
  cache_network_ej:
    driver: bridge
