services:
  db:
    image: mariadb:10.11
    container_name: mariadb_wp
    restart: always
    env_file:
      - .env
    volumes:
      - mi_wordpress_data:/var/lib/mysql
    networks:
      - mi_red_wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_wp
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - mi_red_wordpress

  wordpress:
    image: wordpress:latest
    container_name: wordpress_ejercicio
    restart: always
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mi_red_wordpress

volumes:
  mi_wordpress_data:

networks:
  mi_red_wordpress:
